apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:aTfWYis5aoE=,iv:iCYPQaRgP1GOeUDjW51dWQ+oZ6f7PTZKX1vCQodNKNQ=,tag:m+NTIrnVVKr/c+dNBlzgZg==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:u4ZYjo1iBGi8PemAHte+5iPVtIo5ZIvSCEfkp+HGa3vQkgxL3R4BFjKny1dWsNhJrm8FuBY=,iv:mvquj/4VUS2Mqw6ObjJg3c2NX2e6J0DTG/w1wxi1UB8=,tag:dI7MerzW2fKxTG0FdNXKpg==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:h2VzXAoNz94=,iv:GuXWPAqYNZcTFG15tdAyJmD9HzPR0p7uUYo/0B+/qmw=,tag:K8dN3Ihe8kElaJGmpnkNPQ==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:xqBN5eeKeY4=,iv:pGaxseAoNkZIRQ9/wJfGwTwQh5PXENkT16JG0fbGxx4=,tag:4AVy7a6CY5LwoYj0cX+WIA==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:WWUT99HeWwI=,iv:In1h6W8s53aonS6atmOChGDRKsCvGridgpGDhSnAqeY=,tag:KPW1riSBlbLsz2V2Vni98w==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:9pw5ju1q3oK1,iv:rCon3W98469WPbqifxpZQYbT2w/Ix6BT0Pyp58++s1w=,tag:thZly8GrnfCr8FK9u8MC+w==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:vqCMqomFsyrGRehqFB4UqgFTew==,iv:7YtWEaq0FyW51jK8v2E/UrdEzKOvbxUq24G+BLNWU+4=,tag:pEs7l9BlRM0gfkiwk6uu/w==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:f16ZL0/iyYlMfOi6vu+6,iv:9RVIzDWHnMAITvhNSWBik6npJLuQY7gkUw+hDsFX8U8=,tag:iRwGecBVQRe80EruhrK2Ww==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:CNHQ/RfVPyKren0vYWMn,iv:FGMFV3m8y/aPs1G/ptgg6wgMDtwOJ4jhXFAQlU0XoN4=,tag:n6PKO3Ae1b0g3jj9PBLJcQ==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:ndU9ljaiaY3VWO9H9UnGxy9E2yeW6h6N3Q8fvV/znzZjoTC5,iv:ZGSl5RxaTJkZTn8hRY60XTGaNlrulUS+ar9Srds8680=,tag:pmH1ntJzumLm48x8zgV+2w==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:ydqHHfHcj92Uj9PaZJZL3G99JebTyyTqjFetFBb933VZN8TxZpfBH8y+eb139YMZT2mQmgzkVcUbXnbaVBY6AWUghMYUB+DUX+jkvjPFxKyqcC/9FjIpsKDxDS8+YpnH+6mpLJXpe+W5qiI52d2reWykPnsrTqQJiXEAnDPz1EzxW3njyv7trXSeFNslEn6pC15joueT4Gy7K4ltQYzneVKeIxBgh3SQimAmVB6Siiopc5E=,iv:I6DlN+5N9vcUZr4If83j5gwiul7r3Jq5MJFCYfRTaTw=,tag:wjKp2phpkPila9P0X4DGfg==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:oVaadjzQED9yssDdkYoGjxZZlk5ezZ6uYro28kaBtQLtr8q5KoeDjdTDoTzc92/Y3D1LxAd0BPIpXGW37QGhnCDcE4wkTA==,iv:2oe0UtieCYHhYc27jzlv4X5fnTmg0SNP/eaFurrrcnw=,tag:7wzYwCaUccXBNKvpuN4l3w==,type:str]
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_NOTIFY_GROUP_ID: ""
sops:
  age:
    - recipient: age1ud0tkgu7jdlhj7sd5awu4fktw68g6dpjx36xg5d3yvryx6ktp52sjtqaav
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMmdyTkc2K0RDcjRZQ3dB
        OVVBTlF4TkFqMTIzb0FIR0VRdzlVejkrd0djCnFxNkNZR1U0T0taUTVpS1lGTy9y
        VW9RQ1RXdmdBbWpNNWtPVHJ2dTZsb0kKLS0tIDVmVjhqWWFROWlheDZ1R3R2L0J6
        djZQUFNUOG5GaUM1OUVpQ2pRR3doSlUKF6I8dQXhCSiSil/1k1uwHgMbzBkSkZvd
        7x3u+Z/bcfHphCrwO5YHfDE5Uo+omgoBcDM+QZTyu5AX9bi128X8wQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T06:56:55Z"
  mac: ENC[AES256_GCM,data:zErmyhTfeyYz+f3GIdIbR+SWWSaEoT/9CyrC4W4LeeBMbNi9css5dDymY4xXdPuUpAGiI2o8U4dOQ4wWPKAwkyB+1zjl/LRrj/UKd8r9bxh83wEw7NMCNWSFF1IsxpViVc9geooVPW+Rh4Q2roxdJO5rUO6dN9DV7suk0Fn6ffA=,iv:kBhBFFhPorfNhbH1tAXyR2uXQ+Vbua0h9DitIJQ7YJE=,tag:8PrmHYMA/M1fllXxuExGgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
