apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Hbaxcc/xRfA=,iv:U6lDWSdWJQ1tDFKEqYromti5X7R/HAkLD6zMWTizslo=,tag:lQifoE/nmLPXZ1QonlBvgQ==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ySiQ1XmvAxMJxEjuXNo7ZJhBx2m0tcWhiFgr5IxKQbo8qLYen7tM9xI3e+22r8cn/ifutFk=,iv:Vy1kiBpIMDXSegzb3UeMrRinHrYWsFQKz4wcOX1Abwc=,tag:KVSn4xa+V56okhEikSOZEQ==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:KnxTnc8ieFM=,iv:rqY8QVCnXgbAzhvASStjxL5cTC/rrLgKBqzLbB62Nd4=,tag:510PcKMOUzYA3nxRy0G+Tg==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:gEHMjnH2Q3A=,iv:y8HOILYSzufUEl4dlXd3Edu+Q0x/BIgvLBaLV+DuiV4=,tag:0hBUD6gwSnPCjuOvvPhkhg==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:3W2PWXPBEPA=,iv:41N7DSOvGCZL1bX/2TPQ4G0SzUkT9ul56WtaH/xXqns=,tag:eB97wrr3LGIc3t2dtq9CBQ==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:x0TTCGtIgmHy,iv:lic5c5iMutNPOEN9ffxvala9KNf+rvTdbxerNSAUR7s=,tag:0d/+pyIEfTFb1jDyDUZIzA==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:9fFEeMRXtJlgxf7D+km5J/NykQ==,iv:LE/3v6SVfqvhO7FWwHeDHCMQF/p1w3MWcIUckYVy26o=,tag:5cX6Bn0zPAN2zu8qRrysuw==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:b/2PauBYj+Mm+wlmI2OK,iv:7K8nfk2rop8T9ylS9zluv29TpA+n2IWLEwqKepp3DHM=,tag:sSnlUtgt8Wc2T9eWurLisg==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:QJWY571uocqY66Eo3wYA,iv:XoQBCaybR+TtSf0mhkT3tgK3PuTiUKAs4ygjMZV1b64=,tag:mhyC0d37dCAgAFb4NSsbrA==,type:str]
sops:
  age:
    - recipient: age1ud0tkgu7jdlhj7sd5awu4fktw68g6dpjx36xg5d3yvryx6ktp52sjtqaav
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVDcveFJ2NlpxMGJkcmJi
        Q1U2MU5wbGl1QjJUQ25OYTVzK3cxY0JjSFc0CmF6bTkvYS9mV0Jjb2ttVWxrU2dV
        T0FjdUNQdHI4WGNzWVhwb2h6UC96aGcKLS0tIFF1SUlUUGhWRGNPNWJyT2FSMlVr
        OXY4N3NKU2wwWllTYWZIbitHRFVqdzAKJzO6orZFlE4dFWbdwn+ERNh3xeCW720E
        +0URoWnpc60zXA6pUe0zThid7i+Q4LJa5omRjsJvtOltUHfujUp2fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T02:47:55Z"
  mac: ENC[AES256_GCM,data:PNhSfFjm+VNVtVhc8JFJg3LzSyQ1GQxWMOxa3UX0qiQ2djpeNiHToogXUJkZHal0dO0DSPJ44WnR3QwX7ws46DJYwpvj7toi/JmPv4K1TN5vQIJU4HMnUu4FFquali9kBU82RqCW5ho/5rvaqbPw+YB8DRsAMKJiVkfHtOeKD/Y=,iv:7PnEfXfnO1qBzhHYkVIh41mEAaGjkVvyxhccYLS4Nak=,tag:az+pTWAwocYzOv8Qa8WUww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
