apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:A4Ms1RfxK4w=,iv:Q5ajTSHAMS5Q5T8cvs2rnQvn9s+oNmCS+6SGHnTI9l8=,tag:WGbkDlDY1BHrYqBHYoqlNw==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:8CCGYwobszo6HyFVLZhRO9OIYJlFZez05FH1I1MNG4XrCPvupWzmAT/7jNOOFcuHYYYqIHU=,iv:wcDnafgMxVSZzOdwPPo4EGJCGZsdPmiN5ZtpfdWs8WY=,tag:vz3/0IonetaIFgmtimej2Q==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:JJ+23WF6wD0=,iv:kg5zoDtix3bpqwfHyQzS/JsuA4dIAen/T4Q4NVpsdQQ=,tag:70MND7Zlbx6u38BW9CUXVA==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:r+hmvaYJhuQ=,iv:uT5/cUXGdzQFSuDEoO/DEA4HDWYctct31X4+ozrz46k=,tag:bxC9umV/iN97QfXEYUwFpA==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:pfrhccT72fE=,iv:Q2TSlnaHrMn6NSm3r+JBHvqXx1Vg3T6XApiJbNonXkk=,tag:4XOTub1uT1ZAtaA+Yn7VqQ==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:F0Fhg3lNLOv1,iv:vblkhXeWI8lNdlvXfp7Fue5bMADGXaavDZlg3IREt6Y=,tag:oL4WeIWOdKcgvdMFpQJQQQ==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:bHYOv+m21GR3DQ1fUjauOZAKsQ==,iv:n7BKeKaA+J+om9tpEtLjZ5DVZK1SGSfboiyPS1dH9A0=,tag:wyVyEf+iv09WNqLjKJpdug==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:V4/vMOaBCgeEaDHsy25H,iv:Ui8pPoD7DP4Nt5C60z+Dtrxfx0FncaisCs7AGrLqrng=,tag:bJknLvfeLi0nwCCzET8u+Q==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:SFYg+aae58PUZFYARSP7,iv:UuYZsZ6eSFaZPPdJMqEQRF9/GWXli5fSr1TvT+3tXG4=,tag:suBfTrMOxzQCJr9mMfkiDw==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:ftHYRLisZhflmyHyG0KPSIJEz60SNGX+59Rl3Xb2hzr0iP/a,iv:XRR/NZ16AyP2CJaQZIAS1aFug8Rytl4j27soAOz8MeY=,tag:IAau9ZGrQzx7fLz0xEF3vw==,type:str]
sops:
  age:
    - recipient: age1ud0tkgu7jdlhj7sd5awu4fktw68g6dpjx36xg5d3yvryx6ktp52sjtqaav
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb3paczc4ZlNxVWJlb2dl
        KzhMT1VKa0NUenFwRnR6QjVNTmptMTczNVh3Ck1YcFBhNE5OaUhiMmkxR1dlbXhE
        R1U2M1lFcVBFbmxDSzVoMWkrWHhQbXMKLS0tIHoxRk9Ib2Nnd2thOVVuMmJTb1hJ
        aUxienhUWW02MldVR3psL0pMWCtPSk0KlYLGlN/gHrXL3wScP6rTeBzkGXDaI+kG
        b5uPEEY89Vcw8jFQsV9cVIkT9dFelj9rEvCWPuaHCRP+VttHeK72kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T04:08:03Z"
  mac: ENC[AES256_GCM,data:5VbAxNQGLGrxBchxMvU2aOwZaZ55pSbo8853+clANTaPlSSlDRFiF/DnRQoTRYy2ogzeJhOP8suNVjbSoe4ePFOMTd/P29VUQmKBbPYf6Y9bIg9ATcKSjhK7uGtMwJdHe9QCsIH8WQt+tBRSS+J7mIZHGCkzYe5KxLOxWf69+Z8=,iv:ZjWcMUnGI+26kRUeMCMrU3CuViPixEHXxg7yKrxhHLY=,tag:Kei2sL+XH4+tHxvcP//BfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
